### ISSUE TITLE
Random lower/upper cases when inserting citations 

### ISSUE THREAD

**Issue by sfhd** [davepwsmith/zotpick-applescript#9]
Hi,

thanks a lot for these great scripts! 

I use BBT (1.6.94) to insert citation keys into Scrivener (2.8.1.2) with the help of your scripts (more precisely: zotpick-pandoc for Scrivener.app). My citation key format looks as follows: [auth:lower]:[veryshorttitle:lower]. 

Everything's works fine except the following: each time, I get a different random distribution of lower and upper case letters. Here's what I got after I selected the same reference eight times in a row:

@Hume:treAtise
@HUMe:Treatise
@HUme:treatise
@HUME:TREatise
@HUme:treATIse
@HUme:TREATISE
@hume:trEATISe
@HUME:trEatise

My main question is whether this might happen because of the applescript or because of BBT - and how I could determine the culprit (unfortunately, I don't have any experience with scripts). 

The citation keys show up correctly in Zotero (i.e. 'hume:treatise' in this case), so my suspicion is that this might be a problem with the applescript.

The number of my submitted error report is PK7ZFJR4.

Any suggestions are much appreciated!

Thanks a lot for your help, and sorry if this has nothing to do with the script (I also posted this message to BBT's Github page),

Fabian

**Comment by Jmuccigr** [comment]
Fixed (I think). Please confirm.

**Comment by sfhd** [comment]
Yes, thanks, it's fixed, though I still see only the old scripts in the repository. Does it take some time for them to show?

**Comment by Jmuccigr** [comment]
I might not be doing this right (that is, getting the two repos identical), but it's updated in my repository: https://github.com/Jmuccigr/zotpick-applescript

**Comment by sfhd** [comment]
I have no idea how to do this, either :) But this ticket can be closed, I think. Thanks!

**Comment by davepwsmith** [comment]
@jmuccigr I have set you up as a collaborator on this repository, so you should be able to push updates to it exactly as you would your own. Sorry again that I can't be of more help.

**Comment by Jmuccigr** [comment]
Figured it out and did the merge.
